### ISSUE TITLE
401 Unauthorized

### ISSUE THREAD

**Issue by morcano** [Dewbud/CardConnect#14]
Hey guys! I have an issue with authentication. I'm trying to connect in this way:

`$test = new CardConnect\CardPointe('merchant_id', 'login', 'pwd', 'https://fts-uat.cardconnect.com:6443/');`

But I always get "401 Unauthorized"
I am 100% sure that I entered valid login/pass/merchant ID, but it still not working for me :( 
Can you tell me what could go wrong? Maybe is some initial config missing from the Cardconnect side?

**Comment by rrpadilla** [comment]
Hi @morcano,
I think the issue is you are using your production credentials with the sanbox url:
 SANDBOX URL: ```php https://fts-uat.cardconnect.com/ ```.
 PRODUCTION URL: ```php https://fts.cardconnect.com/ ```.

```php
$client = new CardConnect\CardPointe('merchant_id', 'login', 'pwd', 'https://fts.cardconnect.com/');

if ($client->testAuth()) {
   echo 'AUTH WORKS';
}
```

I recommend you to check the [test class](https://github.com/Dewbud/CardConnect/blob/master/tests/Feature/CardPointeTest.php), everything you need to know is there.

Let me know if works for you.

**Comment by morcano** [comment]
Solved. I used incorrect credentials, sorry 🙄
